#!/usr/bin/env node
/**
 * build-i18n.js — Generate locales/i18n.js from the translation sources.
 *
 * Source of truth:
 *   - locales/<lang>.json        translatable plain strings (managed in Weblate)
 *   - locales/i18n.functions.js  interpolation / plural helpers (dev-managed)
 *
 * Output:
 *   - locales/i18n.js            the `const I18N = { ... }` global the app loads
 *                                (browser <script>); DO NOT edit it by hand.
 *
 * Usage:
 *   node scripts/build-i18n.js           # regenerate locales/i18n.js
 *   node scripts/build-i18n.js --check   # exit 1 if i18n.js is out of sync (CI guard)
 */
'use strict';

const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '..', 'locales');
const functions = require(path.join(localesDir, 'i18n.functions.js'));

// Keep this order stable for a deterministic, diff-friendly output.
const LANGS = ['ko', 'en', 'ja', 'zh', 'pl'];

function serialize(jsonNode, fnNode, indent) {
  const keys = [...new Set([...Object.keys(jsonNode || {}), ...Object.keys(fnNode || {})])];
  let out = '{\n';
  for (const k of keys) {
    const jv = jsonNode ? jsonNode[k] : undefined;
    const fv = fnNode ? fnNode[k] : undefined;
    const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
    const pad = ' '.repeat(indent + 2);
    if (typeof fv === 'function') {
      out += `${pad}${key}: ${fv.toString()},\n`;
    } else if ((fv && typeof fv === 'object') || (jv && typeof jv === 'object' && !Array.isArray(jv))) {
      out += `${pad}${key}: ${serialize(jv || {}, fv && typeof fv === 'object' ? fv : {}, indent + 2)},\n`;
    } else {
      out += `${pad}${key}: ${JSON.stringify(jv)},\n`;
    }
  }
  return out + ' '.repeat(indent) + '}';
}

function build() {
  let body = '';
  body += '// AUTO-GENERATED by scripts/build-i18n.js — DO NOT EDIT.\n';
  body += '// Edit the sources instead, then run: npm run i18n:build\n';
  body += '//   - locales/<lang>.json        translatable strings (managed in Weblate)\n';
  body += '//   - locales/i18n.functions.js  interpolation / plural helpers\n';
  body += '// eslint-disable-next-line no-unused-vars\n';
  body += 'const I18N = {\n';
  for (const lang of LANGS) {
    const json = JSON.parse(fs.readFileSync(path.join(localesDir, `${lang}.json`), 'utf8'));
    body += `  ${lang}: ${serialize(json, functions[lang] || {}, 2)},\n`;
  }
  body += '};\n';
  return body;
}

// Normalize line endings so the sync check is platform-agnostic: Windows CI
// checkouts may rewrite LF -> CRLF, which must not be treated as "out of sync".
const normalizeEol = (s) => s.replace(/\r\n/g, '\n');

const generated = build();
const target = path.join(localesDir, 'i18n.js');

if (process.argv.includes('--check')) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (normalizeEol(current) !== normalizeEol(generated)) {
    console.error('[i18n] locales/i18n.js is OUT OF SYNC with its sources. Run: npm run i18n:build');
    process.exit(1);
  }
  console.log('[i18n] locales/i18n.js is in sync with JSON + functions.');
  process.exit(0);
}

fs.writeFileSync(target, generated, 'utf8');
console.log(`[i18n] wrote ${path.relative(path.join(__dirname, '..'), target)} (${generated.length} bytes)`);
